"use client";
import React, { useRef, useEffect } from "react";
import Head from "next/head";
import Webviewer from "@compdfkit_pdf_sdk/webviewer";

export default function Home() {
  const viewer = useRef(null);
  let docViewer = null;

  useEffect(() => {
    Webviewer.init(
      {
        path: "/",
        pdfUrl: "./example/developer_guide_web.pdf",
        license: "NjZkYzkzOTU1ZTQxZQ==",
      },
      viewer.current
    ).then((instance) => {
      docViewer = instance.docViewer;
      docViewer.addEvent("documentloaded", async () => {
        console.log("ComPDFKit Web Demo loaded");
      });
    });
  });

  return (
    <>
      <Head>
        <title>ComPDFKit Web Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        id="webviewer"
        ref={viewer}
        style={{ height: "100vh", overflow: "hidden" }}
      ></div>
    </>
  );
}
